service: github-backup

provider:
  name: aws
  region: ap-south-1
  ecr:
    images:
      gitbackupimg:
        path: .
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - arn:aws:s3:::github-backup-lkjklasdlfkjasdf/uploads/*

functions:
  backup-worker:
    image:
      name: gitbackupimg
    timeout: 200
    description: sqs for deploy to deploy projects
    ephemeralStorageSize: 5120
    events:
      - sqs:
          arn: arn:aws:sqs:ap-south-1:818682288285:GitBackup
